### PR TITLE
Update schema to match pattern of contact form or email. Closes #69.

### LINKED ISSUE #69: ContactUrl should be checked against email or str
Should check against email or str not url 

```
Schema Validation Error. Type - TestFailureException. Message - Response Schema validation failed for GET /service-info. Details - 1 validation error for TesServiceInfo contactUrl
invalid or missing URL scheme (type=value_error.url.scheme)
```
Seems to be a an issue with email validation in compliance suite

### PR DESCRIPTION
**Pull request by vsmalladi**
@lbeckman314 can you test with Funnel

### CODE REVIEW

**Comment by lbeckman314** [comment]
# Funnel Testing

Currently encountering a "AnyUrl.validate() missing 2 required positional arguments: 'field' and 'config' (type=type_error)" error when running the Service Info test against Funnel.

Will double check Service Info Response and see what may be causing this error. 

# Command Run

```sh
➜ funnel server run

➜ openapi-test-runner report --version 1.1.0  --server "http://localhost:8000/" --include-tags service_info
```

# Test Results ❌

```sh
#################################     Initiating Test-7 for tests/service_info.yml     #################################
YAML file valid for Test: tests/service_info.yml
Running tests for sub-job-1 -> service_info
Sending GET request to http://localhost:8000/v1/service-info. Query Parameters - {}
GET /service-info response status code matched
Compliance Test-7 for tests/service_info.yml failed.
Exception Name - Schema Validation Error. Type - TestFailureException. Message - Response Schema validation failed for GET /service-info. Details - 1 validation error for TesServiceInfo
contactUrl
  AnyUrl.validate() missing 2 required positional arguments: 'field' and 'config' (type=type_error) ❌
```

## Funnel Service Info Response

### Command Run

```sh
➜ curl localhost:8000/service-info
```

### Response

```json
{
  "contactUrl":  "https://ohsu-comp-bio.github.io/funnel/",
  "createdAt":  "2016-03-21T16:27:49-07:00",
  "description":  "Funnel is a toolkit for distributed task execution via a simple, standard API.",
  "documentationUrl":  "https://ohsu-comp-bio.github.io/funnel/",
  "environment":  "development",
  "id":  "org.ga4gh.funnel",
  "name":  "Funnel",
  "organization":  {
    "name":  "OHSU Computational Biology",
    "url":  "https://github.com/ohsu-comp-bio"
  },
  "storage":  [
    "file:///path/to/local/funnel-storage",
    "s3://ohsu-compbio-funnel/storage"
  ],
  "tesResources_backend_parameters":  [
    ""
  ],
  "type":  {
    "artifact":  "tes",
    "group":  "org.ga4gh",
    "version":  "git commit: 356bead5\ngit branch: release/0.11.0\ngit upstream: git@github.com:ohsu-comp-bio/funnel.git\nbuild date: 2024-02-08T19:59:15Z\nversion: 0.11.0"
  },
  "updatedAt":  "2024-04-15T20:22:24-07:00",
  "version":  "git commit: 356bead5\ngit branch: release/0.11.0\ngit upstream: git@github.com:ohsu-comp-bio/funnel.git\nbuild date: 2024-02-08T19:59:15Z\nversion: 0.11.0"
}
```

**Comment by vsmalladi** [comment]
@lbeckman314 any luck with new changes?

**Comment by lbeckman314** [comment]
# Funnel Testing

All Service Info tests passing with Funnel!

# Command Run

## Funnel

```sh
➜ funnel version
git commit: 356bead5
git branch: release/0.11.0
git upstream: git@github.com:ohsu-comp-bio/funnel.git
build date: 2024-02-08T19:59:15Z
version: 0.11.0

➜ funnel server run
```

## OpenAPI

```sh
➜ git checkout vsmalladi/dev

➜ python setup.py install

# Uses added 'service_info' tag
➜ openapi-test-runner report --version 1.1.0  --server "http://localhost:8000/" --include-tags service_info
```

### Service Info Test File

**tests/service_info.yml:**
```yaml
description: Job to retrieve the service info
service: TES
versions:
  - 1.0.0
  - 1.1.0
tags:
  - schema_validation_only
  - service_info    <--- Added tag for testing
```

# Test Results ✅

```sh
#################################     Initiating Test-7 for tests/service_info.yml     #################################
YAML file valid for Test: tests/service_info.yml
Running tests for sub-job-1 -> service_info
Sending GET request to http://localhost:8000/v1/service-info. Query Parameters - {}
GET /service-info response status code matched
Response Schema validation successful for GET /service-info
Compliance Test-7 for tests/service_info.yml successful.
```

**Comment by vsmalladi** [comment]
@uniqueg can you merge?

**Pull request merged**
