### PR TITLE
WIP Add V1.1 feature tests

### PR DESCRIPTION
**Pull request by lbeckman314**
Hello! I'm working on adding `v1.1` support for the test suite to verify [Funnel's](https://github.com/ohsu-comp-bio/funnel) TES compliance as part of @kellrott's lab. This PR is tracking #11 and can hopefully be of use! Happy to add, remove, or edit any changes as you see fit.

The [spec class imports ](https://github.com/elixir-cloud-aai/tes-compliance-suite/commit/504e9baafdd00b769f2efd6a05fe1558d55337c4#diff-7e8f1c427ccc8b0ce90fb40947841835ae31e81ef174054d1041b0d0be694b8eR46-R57) are are all explicitly included for the sake of completeness but can be removed if they're not needed due to `v1.1` being backwards-compatible.  

Currently working on adding tests for the changes listed in the [`v1.1` release page](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1).

### CODE REVIEW

**Comment by lbeckman314** [comment]
# `v1.1` features to be tested ([ref](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1)):

- [ ] Proposal: add "backend_parameters" to tesResources ([#154](https://github.com/ga4gh/task-execution-schemas/pull/154), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R172-R181) / [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R329-R333))
- [ ] Add in new tesState for preempted state. ([#184](https://github.com/ga4gh/task-execution-schemas/pull/184), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R271-R282))
- [ ] feat: allow wildcards in output paths ([#185](https://github.com/ga4gh/task-execution-schemas/pull/185), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R126-R134))
- [ ] Making file type an optional argument ([#155](https://github.com/ga4gh/task-execution-schemas/pull/155), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R105))
- [ ] Changing int64 to int32 for page_size and cpu_count ([#175](https://github.com/ga4gh/task-execution-schemas/pull/175))
- [ ] Adding ignore_error flag ([#159](https://github.com/ga4gh/task-execution-schemas/pull/159), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R59-R62)) 
- [ ] Add CANCELING state to delete cloud resources ([#189](https://github.com/ga4gh/task-execution-schemas/pull/189), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R282))
- [ ] Adding streamable flag to tesInput ([#157](https://github.com/ga4gh/task-execution-schemas/pull/157), [spec](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/14/files#diff-87d529d65e57c8895b5dc5fb934b03a72b922372b6100d4664f4e4eeda319e76R110-R113))
- [ ] Adding filtering features to task listing ([#170](https://github.com/ga4gh/task-execution-schemas/pull/170))

**Comment by uniqueg** [comment]
This is awesome! :rocket:

Welcome @lbeckman314 and please let @LakiG and me know if you need anything. Also, please tag us on any reviews etc.

**Comment by uniqueg** [comment]
Btw, just to let you know: At some point in the not-too-distant future, we will decouple the runner from the tests and so everything TES-specific (models, test cases) will be migrated to a new repo. In this way, we can easily use the same test runner for running compliance tests against other OpenAPI specs like WES. We will of course keep you in the loop when we have a better idea when that will happen. For now, please follow the current structure.

**Comment by lbeckman314** [comment]
Closing for now in favor of PR #29.

**Pull request closed without merging**
